codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,components,files"
  behavior: default
  require_changes: true

component_management:
  individual_components:
    - component_id: js
      name: JavaScript / TypeScript
      paths:
        - sdk/js/src/**
    - component_id: python
      name: Python
      paths:
        - sdk/python/src/**
    - component_id: go
      name: Go
      paths:
        - sdk/go/**
        - "!sdk/go/*_test.go"
    - component_id: java
      name: Java
      paths:
        - sdk/java/src/main/**
    - component_id: csharp
      name: C#
      paths:
        - sdk/csharp/src/**
    - component_id: rust
      name: Rust
      paths:
        - sdk/rust/src/**
    - component_id: php
      name: PHP
      paths:
        - sdk/php/src/**
    - component_id: ruby
      name: Ruby
      paths:
        - sdk/ruby/lib/**
    - component_id: kotlin
      name: Kotlin
      paths:
        - sdk/kotlin/src/main/**
    - component_id: cli
      name: CLI
      paths:
        - cli/**
        - "!cli/**_test.go"

flags:
  js:
    paths:
      - sdk/js/src/
    carryforward: true
  python:
    paths:
      - sdk/python/src/
    carryforward: true
  go:
    paths:
      - sdk/go/
    carryforward: true
  java:
    paths:
      - sdk/java/src/
    carryforward: true
  csharp:
    paths:
      - sdk/csharp/src/
    carryforward: true
  rust:
    paths:
      - sdk/rust/src/
    carryforward: true
  php:
    paths:
      - sdk/php/src/
    carryforward: true
  ruby:
    paths:
      - sdk/ruby/lib/
    carryforward: true
  kotlin:
    paths:
      - sdk/kotlin/src/main/
    carryforward: true
  cli:
    paths:
      - cli/
    carryforward: true
